### ISSUE TITLE
ReadAsync dont work when Release

### ISSUE THREAD

**Issue by lulikin** [Tewr/BlazorFileReader#103] opened 2020-01-14 07:20 UTC
function
 public Task<int> ReadAsync(byte[] buffer, int offset, int count)
works correctly, when I'm in debug mode, but when I'm in release mode or when I publish blazor web assembly project, that function always return 0.
Here is my code :
            ```
            var fs = await files.FirstOrDefault().OpenReadAsync();
            Console.WriteLine(fs.Length);
            byte[] data = new byte[fs.Length];

            long filepos = 0;
            _IsProgressOpened = true;
            byte[] buffer = new byte[1024 * 10];
            using (MemoryStream ms = new MemoryStream())
            {
                int read;
                while ((read = await fs.ReadAsync(buffer, 0, buffer.Length)) != 0)
                {
                    filepos += 1024 * 10;
                    progresval = (int)(filepos * 100 / fs.Length);
                    StateHasChanged();
                    ms.Write(buffer, 0, read);
                    Console.WriteLine("Buffer length " + read);
                }
                Console.WriteLine("File uploaded");
                service.Motive = ms.ToArray();
                Console.WriteLine("File length : " + service.Motive.Length);
                service.MotiveOriginalFileName = originalfilename;
            }
            _IsProgressOpened = false;
            StateHasChanged();
```

**Expected behavior**
Function should work.

**Project type**
Client side

**Environment**
 - Browser: doesn't matter
 - Version of Blazor.FileReader: 1.2.0.19363
 - Version of .net sdk: 3.1.100

**Comment by Tewr** [comment] 2020-01-15 12:31
Sounds like a framework bug but sounds can be deceiving. Ill try to find the time to reproduce in the coming days.

Could you create a small project that reproduces this? Or at least post your full setup? Your setup could possibly affect this - there has been some issues in the framework regarding static resources and release/publish

**Comment by Tewr** [comment] 2020-01-15 15:43
Try the solution in #97 and see if this works for you

Thought it sounded familiar

**Comment by Tewr** [comment] 2020-01-16 23:26
I can't reproduce this. Please provide a full repro project.

**Comment by lulikin** [comment] 2020-01-30 07:25
I changed code. It was working till now (Blazor 3.2)
```
var x = fileReaderService.CreateReference(inputTypeFileElement);
        var files = await fileReaderService.CreateReference(inputTypeFileElement).EnumerateFilesAsync();
        var originalfilename = await jsRuntime.InvokeAsync<string>("getFileNameFromId", inputTypeFileElement);
        if (true)//(files.Count() == 1)
        {
            this.StateHasChanged();
            //var fs = await files.FirstOrDefault().OpenReadAsync();
            //Console.WriteLine(fs.Length);
            //byte[] data = new byte[fs.Length];
            //long filepos = 0;
            _IsProgressOpened = true;
            //byte[] buffer = new byte[1024 * 10];

            service.Motive = (await files.FirstOrDefault().CreateMemoryStreamAsync()).ToArray();
            service.MotiveOriginalFileName = originalfilename;

            //using (MemoryStream ms = new MemoryStream())
            //{
            //    int read;
            //    while ((read = await fs.ReadAsync(buffer, 0, buffer.Length)) > 0)
            //    {
            //        filepos += 1024 * 10;
            //        progresval = (int)(filepos * 100 / fs.Length);
            //        StateHasChanged();
            //        ms.Write(buffer, 0, read);
            //    }
            //    service.Motive = ms.ToArray();
            //    service.MotiveOriginalFileName = originalfilename;
            //}
            _IsProgressOpened = false;
            StateHasChanged();
        }
```
Now I have problem with 'Blazor.platform.findMethod' in javascript, but I see, that this promlem is beeing investigated in another thread.

**Comment by Tewr** [comment] 2020-01-30 09:37
I'm closing this as the original issue is resolved

**Closed as completed by Tewr** 2020-01-30 09:37 UTC
Labels: possible-blazor-issue, need more info
