### ISSUE TITLE
Loading time (CSB).

### ISSUE THREAD

**Issue by thopdev** [Tewr/BlazorFileReader#77] opened 2019-09-04 13:32 UTC
**Describe the bug**
When i try to read a csv file of 40.000kb (360.000 lines) i takes a really long time (couple minutes)

im using:
`new StreamReader(await _fileReference.OpenReadAsync()`

I tried reading by line: 
`var line = await reader.ReadLineAsync();`

or reading by file
`var text = await reader.ReadToEndAsync();` This took 4.03 minutes for 40927219 chars.

My computers does start using more memory but nothing extreme.

**Comment by Tewr** [comment] 2019-09-04 13:52
Are you using server-side or client-side?

Large files on client-side hasn't been a big hit so far, lots of memory is being allocated, nothing is being deallocated, and the GC is overwhelmed. ( `WASM: GC_MINOR: (Nursery full)` messages in the console)

What buffersize have you tried? Does it make any difference? `StreamReader `uses quite a small buffersize by default (`1024kb` I think), you could try to play with it

**Comment by thopdev** [comment] 2019-09-04 14:04
@Tewr Thank you for your response. 

I'm sorry that i did not mention it but i am indeed using client side. 
I tried changing buffersize but that doesn't have that big of an impact.

**Comment by Tewr** [comment] 2019-09-04 14:16
OK thanks. I think this is a general problem with the GC in mono wasm. It's something that has to be rapid on a native level for these kinds of allocations, and WASM has no native support for GC for now, so it's all WASM.

That said, I haven't thought about the speed issues for a while, and if this is really a GC issue (to be confirmed) there might be a way of avoiding said allocations by re-using memory.
[This article](https://blogs.msdn.microsoft.com/mazhou/2018/03/25/c-7-series-part-10-spant-and-universal-memory-management/) specifically adresses the Stream case by using `Memory<byte>` to re-use a memory buffer. It might be worth a shot, shouldn't be too much code, but it's a bit difficult to test.

**Comment by thopdev** [comment] 2019-09-04 14:26
Thank you, ill look into it.

**Comment by thopdev** [comment] 2019-09-05 07:52
https://github.com/aspnet/AspNetCore/issues/10579

.Net Standard 2.0 Doesn't support readAsync(Memory<char[]>

So i don't believe it is possible to do this.

**Comment by Tewr** [comment] 2019-09-08 10:25
Yes I think my comment is a bit out of the blue as well, as the byte array is most likely not the problem, I'm guessing the js interop serialization is more important here, that is, metadata is more damaging than that data itself.

Thinking out loud here...

Maybe there is a possible optimization here as the metadata largely consists of integers. Might be able to skip json serialization which is largely responsible for allocating strings over and over for each call

I wonder if it's possible to allocate an int array for this purpose and skipping arguments all together. Even better, introduce a stateful reference on the js side to the buffer and int array so that a single callback is needed Instead of n times

I'm just not sure on how to profile my code on Monowasm. Gotta read up a bit on the subject

Or I'll just implement those stateful referenced allocations and see if it's faster..

**Comment by Tewr** [comment] 2019-09-11 07:44
Well I tried caching the buffer to minimize callbacks, the code got a lot more complex and interesting, a bit unstable for some reason... but certainly not significantly faster. The GC seems to have the same problems as before. 

I guess as long as I'm not able to profile wasm, it will remain a problem. But I'm open to ideas, PRs, experiments..

**Comment by thopdev** [comment] 2019-09-11 08:17
I did some things on my side to improve it. Its still not as fast as i like but good enough for now.

Thanks for all the help and i hope blazor improves the GC.

**Comment by Tewr** [comment] 2019-09-16 04:29
@hopstar: is there any code or tips you are willing to share?

**Comment by Tewr** [comment] 2019-09-16 13:56
Turns out my Idea about references allocations was on the spot for the meta data, but my implementation lacked the knowledge of the internal apis that could be used. 
This technique is being used [here](https://github.com/SteveSandersonMS/BlazorInputFile/blob/075a154d81192b588164608f9c381bece4d42f5e/BlazorInputFile/wwwroot/inputfile.js#L47) and avoids serialization altogether, by using reflection to be able to use the unmarshaled interfaces (I remember them being out in the open in the early betas of blazor). 

Seeing that the mere reason for the repo in the link above is to address the speed limitation of this and similar libraries, I'm sure there will be a lot of interesting stuff happening here in the near future.

**Comment by Tewr** [comment] 2019-09-18 08:43
Apart from the more efficient calls, @SteveSandersonMS proposes (in his code) to be reading the full file in js at the first call and subsequently chunking only on the .net side (rather than chunking on both sides as I do). I'll have to check what this means for ram (for a 100MB file, wouldn't this technique use a minimum of 100MB of ram on the browser?). If there are no ramifications (pun intended) than I'll switch to his model, this also simplifies the code greatly. But even if there are, it would still be interesting to choose speed over ram usage, in that case should introduce a parameter for the api consumer to choose between speed or RAM.

**Comment by ADefWebserver** [comment] 2019-09-18 11:45
> (for a 100MB file, wouldn't this technique use a minimum of 100MB of ram on the browser?).

I create line of business apps and my users frequently do not have web browsers, or computers, that have a lot of power. Therefore, anything that uses less memory is good for me. So please consider including a parameter that allows me to continue to use the upload control in the present configuration. For server side Blazor it is working great so far and is very fast.

**Comment by Tewr** [comment] 2019-09-18 12:59
@ADefWebserver thank you for the input. In any case, I'm not planning on imposing anything worse than I have already when it comes to RAM usage. I feel like the whole point of using streams is lost if you can't control resource consumption (then just transfer a single huge string and be done with it...). But the GC Pressure overload is very real real quickly on client-side (starting around 5MB something..) so this should be clearly be adressed somehow.

> For server side Blazor it is working great so far and is very fast.

To be clear, for now my thoughts concern only memory-sharing scenarios / client-side blazor (well at least in this thread :) ). Like you said, with a bit of tinkering the SignalR speed can already reach acceptable levels with the current implementation.

**Comment by Tewr** [comment] 2019-09-27 12:52
I tested this in conjunction with TaskManager. Loading a 100MB or even a 400MB arraybuffer has no impact on memory (unless, of course, you read it in to a `MemoryStream`, that will blow up the ram). It make sense as an array buffer is not consumable anyway before loading the bytes using `Uint8Array`. I am pretty confident now that the big gains here have nothing to do with abusing the RAM,  all the gains come from the `InvokeUnmarshalled()` call.

I'm guessing the `arrayBuffer` is just somewhat of a glorified file (section) pointer. When reading [this article](https://www.joji.me/en-us/blog/processing-huge-files-using-filereader-readasarraybuffer-in-web-browser/) you could get the impression that pre-read slicing is necessary, but my tests show that pre-read slicing of the file blob has no impact on memory usage. 

Also, I stated that he was

> subsequently chunking only on the .net side

and now that I've familiarized myself with the code, I realize that it's not true, the chunking is done js side, when initializing `Uint8Array` using an offset.

TL&DR: Obtaining a full `arrayBuffer` has no memory impact, thus pre-read slicing is not necessary.

Some notes: To measure memory, start chrome with `--enable-precise-memory-info` flag, and output `window.performance.memory` in console using 
`Object.defineProperties(window.performance.memory, Object.getOwnPropertyDescriptors(window.performance.memory.__proto__));`

**Comment by Tewr** [comment] 2019-09-30 10:20
@hopstar: Could you post any code I could test? I tried the standard buffersize used by Stream.CopyToAsync (80KB / 81920 bytes) and that speeds up the examples significantly. Even without optimizations I have found that 100Mb should be around 5 seconds. 

Ok so with Steve's interop magic I might get it down to 2 seconds, but we are far from minutes here!

**Comment by SteveSandersonMS** [comment] 2019-09-30 10:26
@Tewr Not sure if you're testing against `localhost`, but if so I'd recommend not doing so. For realistic speed measurements, use a server that's at least about 200ms away from you in ping time, and compare that to native HTTP upload speed to the same server.

**Comment by Tewr** [comment] 2019-09-30 10:43
@SteveSandersonMS: To be clear, I'm only talking about CSB/shared memory. SSB is a different beast, as you stated in your blog post.

**Comment by thopdev** [comment] 2019-09-30 13:27
@Tewr I would love to post some code but its kinda hard as it its requires a few classes from my project, how could i best give it to you? or try to run it myself?

(im reading a csv file and spliting it by delitmeter, then creating objects based on the properties)

**Comment by Tewr** [comment] 2019-10-01 06:31
I created a csv with 450K lines to measure (~40MB). 

For each line i extract one column using string split, parse it to integer, and adds it to a variable. 

Incrementally adding code to measure:
`bufferSize=81920;`
- Just reading raw bytes with 80KB of buffer size: 1.5sec (2sec when cold).
- `using (var sr = new StreamReader(await file.OpenReadAsync(), System.Text.Encoding.UTF8, false, bufferSize))` and `while (null != (line = await sr.ReadLineAsync()))`: 25sec
- Adding `line.Split(';')`: 25sec (so now totalling 50 sec)
- parsing to int, maths etc adds more or less nothing

So unfortunately my conclusion is that all the big numbers comes down to allocating strings...

**Comment by Tewr** [comment] 2019-10-02 09:23
Whenever I get the time (and my head around it) I'm going to do a test with [System.IO.Pipelines](https://devblogs.microsoft.com/dotnet/system-io-pipelines-high-performance-io-in-net/). It wont completely eradicate allocations but I might be able to push them down significantly - assuming that the GC pressure is the culprit we are looking at here, but for the moment it's my only hypothesis.

**Comment by Tewr** [comment] 2019-10-02 12:21
I've been totally nerd sniped on this one (people in threads relating to `Span` and `Memory` keep referring to that xkcd joke)

Anyway, first optimization I found during lunch break:
Replacing `string.Split` with `Span.IndexOf` and `Slice` reduced that second 25 secs penalty to 15 secs.
Here is the method I use to get a field from a line in the CSV (where `n` is the index of the column I want, if you want to read all the columns you would have just to capture each column at the end of the for loop):

 ```
public static ReadOnlySpan<char> GetNthSlice(this ReadOnlySpan<char> source, char c, int n)
        {
            for (int i = 0; i < n; i++)
            {
                var sliceAt = source.IndexOf(c);
                source = source.Slice(sliceAt, source.Length - sliceAt);
            }

            return source.Slice(0, source.IndexOf(c));
        }
```

I've seen that `.net standard 2.1` contains `int.Parse(ReadOnlySpan<char>)` which could speed this up further (I still allocate at least one string ) but I didnt manage to compile the wasm project when targeting 2.1, not sure if its possible..

As this clearly works, further optimization is, to allocate a large string chunk (using `StreamReader.ReadBlockAsync` instead of `ReadLineAsync`), and parse the lines using the same method (this should reduce those first 25 secs). A bit more complicated though, and my lunch break is over...

**Comment by Tewr** [comment] 2019-10-10 10:11
Well, I haven't had the time to  finalize any demo, but I've been fiddling a bit. I don't think readonlyspan is ideal because it get quite complex and not very generic. 

[This guy](https://github.com/indy-singh) has made excellent [write-up up on low-allocation parsing](https://github.com/indy-singh/StringsAreEvil) that could be used. I'ts quite low-level but it may be very interesting in the current CSB implementation.

**Comment by Tewr** [comment] 2021-05-26 19:47
Closing this as the discussion is not very livid

**Closed as completed by Tewr** 2021-05-26 19:47 UTC
Labels: enhancement
